import time

print('ghost coded this in 4 months')
time.sleep(1.0)
print('ARE YOU READY')
input('Yes/No:')
print('i dont care niqqer')
time.sleep(0.4)
print('lets start')
time.sleep(1.5)
print('Do u know html?')
input('U know what to do:')
time.sleep(1.5)
print('Do u know css?')
input('U know what to do:')
time.sleep(1.5)
print('Do u know js?')
input('U know what to do:')
time.sleep(1.5)
print('Do u know php?')
input('U know what to do:')
time.sleep(1.5)
print('congrats,now u can flex with ur full stack developer award')
time.sleep(5.0)
print('claim it here https://marokybot.xyz')